config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#main'

  get '/users/new', to: 'users#new'
  post '/users/new', to: 'users#create'

  get '/users/login', to: 'users#login'
  post '/users/login', to: 'users#login_perform', as: 'users_login_perform'

  post '/users/logout', to: 'users#logout'
  # resource :users

  get '/boards/:id', to: 'boards#show', as: 'boards_show'
  get '/board_threads/new', to: 'board_threads#new'
  post 'board_threads/new', to: 'board_threads#create_new'
  get '/board_threads/:id', to: 'board_threads#show', as: 'board_thread_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { in: 1..255 }
  validates :priority, uniqueness: true

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/board_thread.rb
class BoardThread < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :board

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false },
    length: { in: 3..24 }
  validates :password, presence: true

  validate :validate_username_not_included_in_password

  has_many :board_threads

  private

  def validate_username_not_included_in_password
    if password.include?(username)
      errors.add(:password, 'contains username')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    # return if session[:user_id].blank?
    # return @cached_current_user if @cached_current_user
    # @cached_current_user = User.find_by(id: session[:user_id])

    session[:user_id].present? && (@cached_current_user || (@cached_current_user = User.find_by(id: session[:user_id])))
  end
end

app/controllers/board_threads_controller.rb
class BoardThreadsController < ApplicationController
  def show
    @board_thread = BoardThread.find(params[:id])
  end

  def new
    unless params[:board_id]
      redirect_to root_path
    end
    @thread = BoardThread.new
  end

  def create_new
    unless params[:board_id]
      redirect_to root_path
    end
    permitted_params = params.require(:board_thread).permit(:title, :content, :username, :board_id)
    permitted_params[:board_id] = params[:board_id]
    if current_user
      permitted_params[:username] = current_user.username
      permitted_params[:user_id] = current_user.id
    end
    @thread = BoardThread.new(permitted_params)
    if @thread.save
      flash[:ok] = "Created new thread"
      redirect_to board_thread_show_path(@thread.id)
    else
      flash[:error] = "Couldn't create thread"
      redirect_to board_threads_new_path(board_id: params[:board_id])
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def show
    @board = Board.find(params[:id])
    @board_threads = BoardThread.where(board_id: params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def main
    @boards = Board.order(priority: :asc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    permitted_params = params.require(:user).permit(:username, :password)

    @user = User.new(permitted_params)
    if @user.save
      flash.now[:ok] = 'Created new account'
    else
      flash.now[:error] = "Error creating user: #{@user.errors.full_messages.to_sentence}"
    end

    render :new
  end

  def login
    @user = User.new
  end

  def login_perform
    permitted_params = params.require(:user).permit(:username, :password)

    @user = User.find_by(username: permitted_params[:username])

    if @user&.authenticate(permitted_params[:password])
      flash.now[:ok] = 'You\'re logged in!'
      session[:user_id] = @user.id
    else
      flash.now[:error] = 'Failed to log in'
      @user = User.new
    end

    render :login
  end

  def logout
    if current_user
      reset_session
      flash[:ok] = "Logged out!"
      @user = User.new
    else
      flash[:error] = "Couldn't log you out, you're not logged in"
    end

    redirect_to users_login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_threads_helper.rb
module BoardThreadsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/board_threads/new.html.erb
<h1>Create new thread</h1>
<%= form_for @thread, url: board_threads_new_path(board_id: params[:board_id]), method: :post do |f| %>
	<% unless current_user %>
		<%= f.text_field :username, placeholder: "Username" %><br/><br/>
	<% end %>
	<%= f.text_field :title, placeholder: "Title" %><br/><br/>
	<%= f.text_area :content, placeholder: "Content" %><br/>

	<%= f.submit 'Create thread' %>
<% end %>

app/views/board_threads/show.html.erb
<h1><%= @board_thread.title %></h1>
<h3>created by: <%= @board_thread.username %></h3>
<h2><%= @board_thread.content %></h2>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<h2><%= @board.description %></h2>
<% @board_threads.each do |board_thread| %>
	<fieldset>
		<%= link_to board_thread.title, board_thread_show_path(board_thread) %><br/>
	</fieldset>
	<br/>
<% end %>
<%= link_to "Create new thread", board_threads_new_path(board_id: @board.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<% flash.each do |type, msg| %>
	  <div>
	    <%= msg %>
	  </div>
	<% end %>
	<p><%= link_to 'Home', root_path %> | <%= link_to 'Log in', users_login_path %> | <%= link_to 'Register user', users_new_path %></p>
	<% if current_user %>
	  Logged in as: <%= current_user.username %>
	  <%= link_to 'log out', users_logout_path, method: :post %>
	<% else %>
	  Not logged in
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/main.html.erb
<h1>Hello World!</h1>

<% @boards.each do |board| %>
		<fieldset>
			<%= link_to board.title, boards_show_path(board) %><br/>
			<% if board.description %>
				<small><%= board.description %></small>
			<% end %>
		</fieldset>
	<br/>
<% end %>

app/views/users/login.html.erb
<h2>Login</h2>
<%= form_for @user, url: users_login_perform_path, method: :post do |f| %>
	<%= f.text_field :username, placeholder: "Username" %>
	<%= f.password_field :password, placeholder: "Password" %>

	<%= f.submit 'Log in' %>
<% end %>

app/views/users/new.html.erb
<h2>Create new user</h2>
<%= form_for @user, url: users_new_path, method: :post do |f| %>
	<%= f.text_field :username %>
	<%= f.password_field :password %>

	<%= f.submit 'Register' %>
<% end %>